image: node:latest

stages:
  - build
  - test

before_script:
  - node -v
  - yarn -v
  - yarn

cache:
  paths:
    - node_modules/
    - dist/

build:
  stage: build
  script:
    - yarn build

test:
  stage: test
  script:
    - yarn test 2>&1 | tee test.log
  artifacts:
    paths:
      - test.log

'code quality':
  stage: test
  script:
    - yarn lint
